### PR TITLE
Resolve ens domain

### PR DESCRIPTION
**Pull request by gaurav8628**

### CODE REVIEW

**Comment by zaryab2000** [comment]
@corlard3y please check if we can close this

**Comment by corlard3y** [comment]
Yeah, I believe we can close this, the task was about css fixes and ens domains and it wasn't working as supposed when i checked. So if needed, we can work on implementing it properly in the future @zaryab2000

**Comment by zaryab2000** [comment]
If ENS resolution doesn't work adequately yet, we need to work on fixing this @corlard3y 

Can you check and lemme know the status on ENS resolution on the extension?

**Comment by zaryab2000** [comment]
@corlard3y please check if  this can be closed now

**Comment by corlard3y** [comment]
It can be closed. Unable to run this branch and the implementation can be done more technically if the feature is needed.

**Pull request closed without merging**
